[project]
name = "agentharm-repro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.49.0",
    "inspect-ai>=0.3.79",
    "openai>=1.69.0",
    "pandas>=2.2.3",
]
